#!/bin/bash -x

# Build artifact version
SHORT_COMMIT=$(cut -c1-8 <<<"$COMMIT")
VERSION="1.0.$BUILD_NUMBER-$SHORT_COMMIT"
if [ "$BRANCH" != "master" ]; then
    VERSION="${VERSION}-${BRANCH}"
fi

# The file named version is used by Jenkins job-specific configuration
# to display version
echo -n $VERSION > version

echo "version = '$VERSION'" > version.gradle
ssh-keyscan github.com >> /root/.ssh/known_hosts
gradle build publishToGithub
